spring:
  application:
    name: order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8702
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClientName: com.netflix.loadbalancer.RandomRule
env:
  test3
label:
  release

entity:
  name: config
  version: one
